In [1]:
!pip install tensorflow==2.0.0-beta1

In [0]:
import tensorflow as tf

In [3]:
print(tf.executing_eagerly())

True


In [0]:
x = [[2.]]
m = tf.matmul(x, x)

In [5]:
print("hello, {}".format(m)) 
print("m:",m.numpy())

hello, [[4.]]
m: [[4.]]


In [0]:
a = tf.constant([[1,2],[3,4]])

In [7]:
print(a) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [0]:
b = tf.add(a, 1)

In [9]:
print(b) 
print()

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)



In [0]:
def fizzbuzz(max_num):
  counter = tf.constant(0)
  max_num = tf.convert_to_tensor(max_num)
  for num in range(1, max_num.numpy()+1):
    num = tf.constant(num)
    if int(num % 3) == 0 and int(num % 5) == 0:
      print('3과 5의 배수')
    elif int(num % 3) == 0:
      print('3의 배수')
    elif int(num % 5) == 0:
      print('5의 배수')
    else:
      print(num.numpy())
    counter += 1

In [11]:
fizzbuzz(15)

1
2
3의 배수
4
5의 배수
3의 배수
7
8
3의 배수
5의 배수
11
3의 배수
13
14
3과 5의 배수


In [13]:
print()
print('Computing gradients')
W = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
  loss = W * W

grad = tape.gradient(loss, W)
print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)


Computing gradients
tf.Tensor([[2.]], shape=(1, 1), dtype=float32)
