In [0]:
!pip install tensorflow==2.0.0-beta1

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
# List
L0 = 3. # a rank 0 tensor; this is a scalar with shape []
L1 = [1. ,2., 3.] # a rank 1 tensor; this is a vector with shape [3]
L2 = [[1., 2., 3.], [4., 5., 6.]] # a rank 2 tensor; a matrix with shape [2, 3]
L3 = [[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]] # a rank 3 tensor with shape [2, 1, 3]
L4 = [[[[1., 2],[3., 4.]], [[5., 6.],[7., 8]]], 
      [[[9., 10],[11., 12.]], [[13., 14.],[15., 16]]]]

In [0]:
print(type(L0))
print(type(L1))
print(type(L2))
print(type(L3))
print(type(L4))
print()

<class 'float'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>



In [0]:
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Numpy
N0 = np.array(L0)
N1 = np.array(L1)
N2 = np.array(L2)
N3 = np.array(L3)
N4 = np.array(L4)

In [0]:
print(type(N0))
print(type(N1))
print(type(N2))
print(type(N3))
print(type(N4))
print()

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>



In [0]:
print('---------- Numpy dim -----------------')
print(N0.ndim)
print(N1.ndim)
print(N2.ndim)
print(N3.ndim)
print(N4.ndim)
print()

---------- Numpy dim -----------------
0
1
2
3
4



In [0]:
print('---------- Numpy shape ---------------')
print(N0.shape)
print(N1.shape)
print(N2.shape)
print(N3.shape)
print(N4.shape)
print()

---------- Numpy shape ---------------
()
(3,)
(2, 3)
(2, 2, 3)
(2, 2, 2, 2)



In [0]:
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Tensorflow
T0 = tf.constant(N0)
T1 = tf.constant(N1)
T2 = tf.constant(N2)
T3 = tf.constant(N3)
T4 = tf.constant(N4)

In [0]:
print("---------- Tensorflow -------------")
print(T0)
print(T1)
print(T2)
print(T3)
print(T4)
print()

---------- Tensorflow -------------
tf.Tensor(3.0, shape=(), dtype=float64)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float64)
tf.Tensor(
[[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]], shape=(2, 2, 2, 2), dtype=float64)



In [0]:
print("---------- Tensorflow rank -------------")
print(tf.rank(T0), tf.rank(T0).numpy())
print(tf.rank(T1), tf.rank(T1).numpy())
print(tf.rank(T2), tf.rank(T2).numpy())
print(tf.rank(T3), tf.rank(T3).numpy())
print(tf.rank(T4), tf.rank(T4).numpy())
print()

---------- Tensorflow rank -------------
tf.Tensor(0, shape=(), dtype=int32) 0
tf.Tensor(1, shape=(), dtype=int32) 1
tf.Tensor(2, shape=(), dtype=int32) 2
tf.Tensor(3, shape=(), dtype=int32) 3
tf.Tensor(4, shape=(), dtype=int32) 4



In [0]:
print("---------- Tensorflow shape -------------")
print(T0.shape, tf.shape(T0), tf.shape(T0).numpy())
print(T1.shape, tf.shape(T1), tf.shape(T1).numpy())
print(T2.shape, tf.shape(T2), tf.shape(T2).numpy())
print(T3.shape, tf.shape(T3), tf.shape(T3).numpy())
print(T4.shape, tf.shape(T4), tf.shape(T4).numpy())
print()
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#float_tensor = tf.cast(tf.constant([1, 2, 3]), dtype=tf.float32)

---------- Tensorflow shape -------------
() tf.Tensor([], shape=(0,), dtype=int32) []
(3,) tf.Tensor([3], shape=(1,), dtype=int32) [3]
(2, 3) tf.Tensor([2 3], shape=(2,), dtype=int32) [2 3]
(2, 2, 3) tf.Tensor([2 2 3], shape=(3,), dtype=int32) [2 2 3]
(2, 2, 2, 2) tf.Tensor([2 2 2 2], shape=(4,), dtype=int32) [2 2 2 2]



In [0]:
print("------------- Tensorflow -> Numpy -------------")
print(type(T2.numpy()), T2.numpy(), np.array(T2))
print(type(T4.numpy()), T4.numpy(), np.array(T4))
print((T2+T2).numpy())
print()

------------- Tensorflow -> Numpy -------------
<class 'numpy.ndarray'> [[1. 2. 3.]
 [4. 5. 6.]] [[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'> [[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]] [[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]



In [0]:
print("------------- Numpy -> Tensorflow -------------")
print(type(tf.constant(N2)), tf.constant(N2))
print(type(tf.constant(N4)), tf.constant(N4))
print(tf.add(T2, T2))

------------- Numpy -> Tensorflow -------------
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor(
[[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]], shape=(2, 2, 2, 2), dtype=float64)
tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float64)
