In [2]:
!pip install tensorflow==2.0.0-beta1

In [0]:
import tensorflow as tf
import numpy as np

In [4]:
print("********** rank 1 - Numpy ****************")

t1 = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t1)
print(t1.ndim) # rank
print(t1.shape) # shape
print(t1[0], t1[1], t1[-1])
print(t1[2:5], t1[4:-1])
print(t1[:2], t1[3:])
print()

********** rank 1 - Numpy ****************
[0. 1. 2. 3. 4. 5. 6.]
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]



In [6]:
print("********** rank 2 - Numpy ****************")
t2 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t2)
print('rank = ', t2.ndim) # rank
print('shape = ', t2.shape) # shape
print()

********** rank 2 - Numpy ****************
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
rank =  2
shape =  (4, 3)



In [7]:
print("********** rank 1 - Tensor ****************")
t1_1 = tf.constant([1,2,3,4])
print(t1_1)
print('rank = ', tf.rank(t1_1).numpy())
print('shape = ', t1_1.shape)
print()

********** rank 1 - Tensor ****************
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
rank =  1
shape =  (4,)



In [8]:
print("********** rank 2 - Tensor ****************")
t2_1 = tf.constant([[1,2], [3,4]])
print(t2_1)
print('rank = ', tf.rank(t2_1).numpy())
print('shape = ', t2_1.shape)
print()

********** rank 2 - Tensor ****************
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
rank =  2
shape =  (2, 2)



In [9]:
print("********** rank 3 - Tensor ****************")
t3 = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(t3)
print('rank = ', tf.rank(t3).numpy())
print('shape = ', t3.shape)
print()

********** rank 3 - Tensor ****************
tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)
rank =  4
shape =  (1, 2, 3, 4)



In [10]:
print("********** rank 4 - Tensor ****************")
t4 = tf.constant([
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
])
print(t4)
print('rank = ', tf.rank(t4).numpy())
print('shape = ', t4.shape)
print()

********** rank 4 - Tensor ****************
tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)
rank =  4
shape =  (1, 2, 3, 4)



In [11]:
print("********** matmul ****************")
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.],[2.]])
matmul = tf.matmul(matrix1, matrix2)
print(matrix1)
print(matrix2)
print(matmul)
print()

********** matmul ****************
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.]
 [2.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[ 5.]
 [11.]], shape=(2, 1), dtype=float32)



In [12]:
print("********** multiply & Broadcasting ****************")
multiply1 = matrix1*matrix2
print(multiply1)
multiply2 = tf.multiply(matrix1, matrix2)
print(multiply2)
print()

********** multiply & Broadcasting ****************
tf.Tensor(
[[1. 2.]
 [6. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [6. 8.]], shape=(2, 2), dtype=float32)



In [13]:
print("********** Add ****************")
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
matadd2 = matrix1+matrix2
print(matadd2)
print()

********** Add ****************
tf.Tensor([[2. 2.]], shape=(1, 2), dtype=float32)



In [14]:
print("********** Add & Broadcasting ****************")
# Broadcasting
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
matadd1 = matrix1+matrix2
print(matadd1)
print()

********** Add & Broadcasting ****************
tf.Tensor(
[[5. 5.]
 [5. 5.]], shape=(2, 2), dtype=float32)



In [15]:
print("********** range ****************")
start=3
limit=18
steps=3
print(tf.range(start, limit, steps)) # [3, 6, 9, 12, 15]

start=3
limit=1
steps=-0.5
print(tf.range(start, limit, steps)) # [3, 2.5, 2, 1.5]

limit=5
print(tf.range(limit)) # [0, 1, 2, 3, 4]
print()

********** range ****************
tf.Tensor([ 3  6  9 12 15], shape=(5,), dtype=int32)
tf.Tensor([3.  2.5 2.  1.5], shape=(4,), dtype=float32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)



In [16]:
print("********** random number generation ****************")
#%%

print(tf.random.normal([3]).numpy())
print(tf.random.uniform([2]))
print(tf.random.uniform([2, 3]))
print()

********** random number generation ****************
[ 1.5438304  -1.2550997   0.04014904]
tf.Tensor([0.5478959 0.9767009], shape=(2,), dtype=float32)
tf.Tensor(
[[0.0432241  0.4815148  0.15564692]
 [0.553208   0.9218986  0.14146948]], shape=(2, 3), dtype=float32)



In [17]:
print("********** reduce mean & axis ****************")

x = [[1., 2.],
     [3., 4.]]

print(tf.reduce_mean(x))
print(tf.reduce_mean(x, axis=0)) # axis=0으로 reduce mean
print(tf.reduce_mean(x, axis=1)) # axis=1로 reduce mean
print()

********** reduce mean & axis ****************
tf.Tensor(2.5, shape=(), dtype=float32)
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)



In [18]:
print("********** Reshape ****************")
# reshape

t = tf.constant([[[0, 1, 2],
               [3, 4, 5]], 
              [[6, 7, 8],
               [9, 10, 11]]])

print(tf.shape(t))

print(tf.reshape(t, shape=[-1]))
print(tf.reshape(t, shape=[-1, 2]))
print(tf.reshape(t, shape=[-1, 3]))
print(tf.reshape(t, shape=[-1, 1, 3]))

print(tf.squeeze([[0], [1], [2]]))
print(tf.expand_dims([0, 1, 2], 1))
print()

********** Reshape ****************
tf.Tensor([2 2 3], shape=(3,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]], shape=(6, 2), dtype=int32)
tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]], shape=(4, 1, 3), dtype=int32)
tf.Tensor([0 1 2], shape=(3,), dtype=int32)
tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)



In [19]:
print("********** One hot ****************")

print(tf.one_hot([[0], [1], [2], [0]], depth=3))
print()

********** One hot ****************
tf.Tensor(
[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]], shape=(4, 1, 3), dtype=float32)



In [20]:
print("********** Casting ****************")

print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32))
print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32))
print()

********** Casting ****************
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)



In [21]:
print("********** Stack ****************")

x = [1, 4]
y = [2, 5]
z = [3, 6]

print(tf.stack([x, y, z]))
print()

********** Stack ****************
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)



In [22]:
print("********** Ones and Zeros like ****************")

x = [[0, 1, 2],
     [2, 1, 0]]

print(tf.ones_like(x)) # 1로 채운
print(tf.zeros_like(x)) # 0으로 채운
print()


********** Ones and Zeros like ****************
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)



In [23]:
print("********** Zips ****************")

for x, y in zip([1, 2, 3], [4, 5, 6]): # x와 y에 담아서 처리
  print(x, y)


********** Zips ****************
1 4
2 5
3 6
