In [1]:
!pip install tensorflow==2.0.0-beta1

In [0]:
import tensorflow as tf

In [0]:
# tensor variable 
t1 = tf.Variable(42) 
t2 = tf.Variable([1.,-1])
t3 = tf.Variable([[1.,-1.],[-1., 2]])
t4 = tf.Variable([[[0., 1., 2.],[3., 4., 5.]],[[6., 7., 8.],[9., 10., 11.]]]) 

In [4]:
print(t1)
print(t2)
print(t3)
print(t4)
#print(t1.shape, tf.rank(t1).numpy(), t2.shape, tf.rank(t2).numpy())

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([ 1., -1.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1., -1.],
       [-1.,  2.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


In [0]:
t1 = tf.add(t1, 1)
t2 = tf.add(t2, 1.0)
t3 = tf.add(t3, t2)

In [6]:
print(t1)
print(t2)
print(t3)

tf.Tensor(43, shape=(), dtype=int32)
tf.Tensor([2. 0.], shape=(2,), dtype=float32)
tf.Tensor(
[[ 3. -1.]
 [ 1.  2.]], shape=(2, 2), dtype=float32)
